#! /bin/bash 
# This script is used to remove the memory cache
# To free pagecache: 
sync 
sync 
#echo 1 > /proc/sys/vm/drop_caches 
# To free dentries and inodes: 
#echo 2 > /proc/sys/vm/drop_caches 
# To free pagecache, dentries and inodes: 
echo 3 > /proc/sys/vm/drop_caches 
echo 0 > /proc/sys/vm/drop_caches 
exit 0
